### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by schubertr** [ashish2199/snake_game_applet#1]
I saw your post on /r/progether:

http://www.reddit.com/r/progether/comments/323hjh/recruiting_snake_game_using_java_swing/

and would like to help if you need it. Are there any bugs or anything that need attention?

**Comment by ashish2199** [comment]
Thanks,
Yeah I am still working on this but I am not able to devote much time to it now as my exams are approaching soon.
Yeah I do have some bugs, 
The most irritating one being the Game not responding to keyboard input after starting the game. It requires a minimize ( that is a repaint ) in order for it to take input from keyboard.

Btw are you able to understand my code :P because I do quick dirty coding being a newbie.
